### ISSUE TITLE
CMake does not compile

### ISSUE THREAD

**Issue by sresam89** [CSS-Electronics/mdf4-converters#1]
when doing a configure using
```
cmake Tools

CMake error at Tool/CMakeLists.txt:30 (pack_executable):
Unknown CMake command pack_executable 
```

```
cmake --verison
cmake version 3.10.2
```

```
g++ --version
g++ ubuntu 7.4.0.-1ubuntu~18.04.1) 7.4.0
```

**Comment by MatinF** [comment]
@sresam89 Thanks for the feedback, we'll look into this in the upcoming next release.

**Comment by MatinF** [comment]
@sresam89 can you try this out again with the latest builds? A lot of refactoring of the codebase has been done since last time.

**Comment by MatinF** [comment]
Closing this for now

**Comment by angelo0027** [comment]
I encountered the same issue in 3.19.0-rc1 on Windows 10 x64

```
CMake Error at CMakeLists.txt:32 (pack_executable):
  Unknown CMake command "pack_executable".
```

**Comment by MatinF** [comment]
@angelo0027 just to check, are you sure you're using the latest version of the master? Can you let us know the specific steps you take in order for us to replicate this?
