### ISSUE TITLE
Feature request: Human readable datetime output

### ISSUE THREAD

**Issue by FunDeckHermit** [CSS-Electronics/mdf4-converters#3]
Hello,

We just bought the CanEdge2 and are trying different file outputs. All of them seem to convert the time to an Unix timestamp. 

If would be nice to have a command line argument to specify the date output or just change it to a somewhat readable format.

**Comment by MatinF** [comment]
Hi there, thanks for the feedback.

Most of the formats are "locked" in terms of the output style, given that the data formats need to fit e.g. Vector, PEAK and other tools. The CSV style output could potentially be modified to include a more readable date-time style output, which we'll consider for future feature updates. What format do you believe would be more useful?

Note that you can also load the raw log file data in the asammdf GUI and export it to CSV with absolute date & time added. Similarly, you can load the data using the Python API (see our [api-examples](https://github.com/CSS-Electronics/api-examples)) and save it as CSV with the time format you prefer.

Let me know if one of the above would be an alternative option. If you can let me know in what way you'd want to use the converted raw data, that might also be helpful for our understanding/context.

**Comment by FunDeckHermit** [comment]
Hello Matin,

That's a quick response. 

We are debugging an automotive embedded device which seems to have a somewhat erratic fault. The data would just be viewed in Excel or Notepad++. I suspect converting this many lines of logdata in Excel would not work very well. 

Scooping the C++ code into our Delphi IDE was something we considered. I have some experience in Python and could write a simple script to convert the MDF4 files, I'm afraid Python would take while with the amount of data on an SD card. 

If you want to implement it in a future release then this format would be best in our usecase: "2020-11-25 15:27:15 365289"

**Comment by MatinF** [comment]
If you're simply looking for ad hoc reviewing the raw data, I suggest checking the asammdf GUI tabular display. You could e.g. concatenate multiple log files into one file and then use the tabular view filters to analyse the raw data. For details, see the CANedge Intro Process section.

I think our Python script would be a fairly efficient way to process the data as it's optimized for speedy loading and decoding. If you give it a try, you're welcome to reach out with any questions/reflections.

We'll note your suggestion for future feature updates of the `mdf2csv` converter.

**Comment by FunDeckHermit** [comment]
Hello Matin,

Based on your feedback we decided to give the asammdf GUI another try. We had seen the [video ](https://canlogger.csselectronics.com/canedge-getting-started/log-file-tools/asammdf-gui/) but were unable to recreate the tabular view. The "Selec... window" with the dropdown did not appear in our application. 

By trail and error we stumbled upon the "Create Window" button on the bottom right of the screen. This was the missing link to create a tabular view. 

The tabular view does seem to have a bug when scrolling down. The view resets to the top of the data.

**Comment by MatinF** [comment]
Hm the select window should come when you drag & drop the channel group onto the gray area - is this not the case for you in v5.23.1 of asammdf? Also, note that there are subsections in the documentation for the different parts of asammdf, incl. the section [Load raw data](https://canlogger.csselectronics.com/canedge-getting-started/log-file-tools/asammdf-gui/raw-mdf4/) where we explain how to use the tabular view in more detail.

**Comment by FunDeckHermit** [comment]
The drop & drag interaction was not intuitive or clearly appearent for us
based on the video.

We gave it a shot and it didn't work so we dropped it. I'm glad we gave it
a second try based on your recommendation.

Op wo 25 nov. 2020 19:01 schreef Martin Falch <notifications@github.com>:

**Comment by MatinF** [comment]
Ok thanks for the feedback, will make a note of this :-)
