### ISSUE TITLE
mdf-iter module not available on linux

### ISSUE THREAD

**Issue by hermann4** [CSS-Electronics/mdf4-converters#4]
I'd like to install your mdf4-converters toolset, but I cannot find a compatible version of mdf_iter, neither for linux amd64 or (preferable) for ARM. Also I can not find the sources mentioned in the Readme. Is there any way for you to provide those? Or could you say where I can find them? Thank you very much!

**Comment by MatinF** [comment]
Hi there,

Are you looking to use the converter executables? If so they are available in the releases page.

If you're aiming to use the mdf_iter Python module, you can pip install it via mdf_iter as described here:
https://pypi.org/project/mdf-iter/

You can see our api-examples repo for examples of use.

**Comment by hermann4** [comment]
> Hi there,
> 
> Are you looking to use the converter executables? If so they are available in the releases page.
> 
> If you're aiming to use the mdf_iter Python module, you can pip install it via mdf_iter as described here:
> https://pypi.org/project/mdf-iter/
> 
> You can see our api-examples repo for examples of use.

Hi Martin,

thank you really much for your reply. I'm having problems getting mdf-iter to work, cause the provided wheels are just for windows (v0.0.2) or linux (v0.0.1), and compiled for the wrong architecture in this case. As mentioned below I have to compile them from source, but I cannot find it. My goal is to get can-decoder running on an ARM- machine.
I hope I don't miss something obvious here, but I either need the source or find a way to recompile the wheel for mdf-iter for ARM I guess? `pip install mdf-iter` is not working for me, neither on Debian amd64 nor on ARM. 
`Collecting mdf_iter
  Could not find a version that satisfies the requirement mdf_iter (from versions: )
No matching distribution found for mdf_iter`

**Comment by MatinF** [comment]
Hi again,

It's possible that the build environments you mention are not currently supported. Can you detail the use case you're trying to achieve with the converters, just for our context? Then I can discuss with the team.

best,
Martin

**Comment by hermann4** [comment]
Thank you! My plan is quite simple: Right now we're using four canedge2- loggers and I'd like to decode them using our DBC- File and upload this data to our InfluxDB. This should run automatically.

**Comment by MatinF** [comment]
Ok, can you let me know what S3 server type you're using? If you're on AWS, I suggest checking out our AWS Lambda example. It would allow for automatic processing of the incoming data and the dependencies are built for use on that environment.

https://github.com/CSS-Electronics/dashboard-writer/tree/master/dashboard-writer/aws_lambda_example

Let me know if that is an option,
Martin

**Comment by hermann4** [comment]
Unfortunately we are using a self- hosted minio- server.
You you have the sources for mdf_iter available? The easiest option could be to compile it from source I guess?
Another way I thought of is using asammdf to convert the data, though I couldn't find any documentation to do that on the terminal.

**Comment by MatinF** [comment]
Hi again,

We've updated the README to explain how you go through the build process - hope you'll be able to build it for your system based on this: https://github.com/CSS-Electronics/mdf4-converters

best,
Martin

**Comment by hermann4** [comment]
Thank you very much! This worked for me

**Comment by ROVSoftware** [comment]
> Thank you very much! This worked for me

I have a similar problem with my RPi installation. Would you mind sharing your MDF-iter compiled installation that can be installed on the Linux AMD Raspberry Pi?

Thanks

**Comment by MatinF** [comment]
Hi again,

We do not have an updated pre-compiled version of it - but you should be able to build it as per the outline in this ticket. With the next update, we may add a RPi built version as well.
