### ISSUE TITLE
Feature Request: macOS Support

### ISSUE THREAD

**Issue by hmitsch** [CSS-Electronics/mdf4-converters#7]
## Current State
The MDF4 converter is currently supporting Windows and Linux only.

## Desired State
The MDF4 converter also works on macOS.

@MatinF, would you be able and willing to look into this?

**Comment by mkabelitz** [comment]
To add to @hmitsch's comment, trying to pip install on macOS leads to the following outcome:
```
$ pip install mdf-iter
ERROR: Could not find a version that satisfies the requirement mdf-iter (from versions: none)
ERROR: No matching distribution found for mdf-iter
```
which is expected since on [PyPI](https://pypi.org/project/mdf-iter/#files) the only listed distributions are Windows and Linux.

**Comment by MatinF** [comment]
Hi guys, thanks for the inputs!

We do not currently have plans to add support for Mac as our core focus is on Windows/Linux, with Mac users being very niche in our segment. Further, it is not within our core team expertise to build tools for use on Mac. 

With that said, you might be able to build the mdf-iter module on Mac assuming you have experience with doing this from past projects - or you may be able to find e.g. a freelancer or similar with experience in this area.

Further, if the aim is to use the modules for e.g. processing data from S3, you can consider using e.g. AWS Lambda functions to avoid having to install anything locally on Mac.

I hope you'll find a solution.
